url: https://creativetours.eu
baseurl: 

# Site settings
brand: "Тренинг-тур в Грузию"
title: "Тренинг-тур в Грузию с 27 октября по 2 ноября 2019"
email: teatral.tallinn@gmail.com
description: "Мастер-классы по актерскому мастерству для энтузиастов и начинающих, приправленные красотами Грузии."
thumbnail: "/img/site-thumbnail.png"

google_tag: UA-124908281-3
yandex_tag: 52496866

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: "http://www.instagram.com/magic_gruzija?hl=ru"
  - title: envelope
    url: "mailto:teatral.tallinn@gmail.com"
  - title: phone
    url: "tel:+37255994317"

# ideal image slider
iis_slider_enabled: 1
iis_slider_array: []

# Build settings
markdown: kramdown
permalink: pretty

