url: https://creativetrours.eu
baseurl: 

# Site settings
title: Тренинг-тур в Грузию
email: teatral.tallinn@gmail.com
description: "Мастер-классы по актерскому мастерству, приправленные красотами Грузии."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://www.instagram.com/magic_gruzija
  - title: envelope
    url: mailto:teatral.tallinn@gmail.com
  - title: phone
    url: callto:+37255994317

# Build settings
markdown: kramdown
permalink: pretty